services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lll
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
