spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lll
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: 86400
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        sql: DEBUG