spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lll
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        sql: DEBUG